version: '3.8'

services:
  # 1. OpenSearch (DB)
  opensearch-node:
    build:
      context: ./opensearch
#      platforms:
#        - linux/amd64
#        - linux/arm64
    container_name: opensearch-node
    env_file: .env
    environment:
      - TZ=Asia/Seoul
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "${OPEN_SEARCH_PORT_1}:9200"
      - "${OPEN_SEARCH_PORT_2}:9600"
    volumes:
      - "${UPLOAD_PATH}/search:/usr/share/opensearch/data"
    networks:
      - search-net

  # 2. Search Intelligence (Python)
  search-intelligence:
    build:
      context: ./search-intelligence
      dockerfile: Dockerfile
#      platforms:
#        - linux/amd64
#        - linux/arm64
    container_name: search-intelligence
    env_file: .env
    ports:
      - "${EMBEDDING_PORT}:8000"
    environment:
      - TZ=Asia/Seoul
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - ${UPLOAD_PATH}/embedding-model:/root/.cache/huggingface
    networks:
      - search-net

  # 3. Search Manager (Spring Boot)
  search-manager:
    build:
      context: .
      dockerfile: Dockerfile
#      platforms:
#        - linux/amd64
#        - linux/arm64
    container_name: search-manager
    env_file: .env
    ports:
      - "${SERVER_PORT}:80"
    environment:
      - TZ=Asia/Seoul
      # Override hosts for container networking
      - OPEN_SEARCH_HOST=opensearch-node
      - SEARCH_INTELLIGENCE_HOST=http://search-intelligence
      - UPLOAD_PATH=/app/upload # 컨테이너 내부에서 사용될 UPLOAD_PATH
      - SEARCH_INDEXES_FILE_LOCAL_PATH_PREFIX=/Users/centerlink/app/upload # localPathPrefix 명시적 설정
    depends_on:
      - opensearch-node
      - search-intelligence
    volumes:
      - "${UPLOAD_PATH}:/app/upload" # 호스트의 UPLOAD_PATH를 컨테이너의 /app/upload로 마운트
    networks:
      - search-net

volumes:
  opensearch-data:
  huggingface-cache:

networks:
  search-net:
    name: havana-network
    external: true